### ISSUE TITLE
aoscx_backup_config: backing up cli config doesn't work

### ISSUE THREAD

**Issue by cs-1** [aruba/aoscx-ansible-role#19]
We use the following tasks to back up switch configurations for Aruba CX switches:

```YAML
- name: Fetch JSON backup from switch
  arubanetworks.aoscx.aoscx_backup_config:
    config_name: running-config
    output_file: "{{ inventory_hostname }}.json"
    config_type: json

- name: Fetch CLI backup from switch
  arubanetworks.aoscx.aoscx_backup_config:
    config_name: running-config
    output_file: "{{ inventory_hostname }}.cli"
    config_type: cli
```

While the first task works as expected, the second task only produces the JSON version of the config, not the cli version. Is this a bug? According to the docs, this should work.
